PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX schema: <http://schema.org/>
PREFIX dbo: <http://dbpedia.org/ontology/>
PREFIX ex: <http://www.example.com/res/>

# See dbpedia_node_* queries. This is a set of queries for a subset of data, to show how you can use 
# MultiConfigCyLoader to load data from different query sets (see also multi_config.xml) 
#
SELECT DISTINCT ?iri
{
  # This picks up nodes of interests based on their rdf:type, which should be pretty common.
  #
  { ?iri a schema:Person }
  
  # This instead selects nodes of interest based on the range of a property (i.e., we're interested in in resources
  # used as target of the dbo:team property, which are assumed to be teams.
  #  
  UNION { ?team dbo:team ?iri }
  
  # Another case based on rdf:type 
  UNION { ?iri a ex:Topic } 
}
